# filepath: render.yaml
services:
  - type: web
    name: bloom-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bloom_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bloom_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bloom-db
          property: connectionString
databases:
  - name: bloom-db
    plan: free